# Generated by Django 4.1 on 2022-10-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdb',
            name='shortcontent',
        ),
        migrations.RemoveField(
            model_name='newsdb',
            name='teg',
        ),
        migrations.AlterField(
            model_name='newsdb',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newsdb',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profiledb',
            name='characters',
            field=models.CharField(max_length=20),
        ),
    ]
