# Generated by Django 4.1 on 2022-10-23 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_newsdb_shortcontent_remove_newsdb_teg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latterstorector',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='latterstorector',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
