# Generated by Django 4.1 on 2022-10-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_latterstorector_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latterstorector',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
